// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPdA-KTnqbFqWzy6xsbJ9mSPDc2Z_lMo8',
    appId: '1:861577509887:web:a48a51e0b2bce4bdbec5ca',
    messagingSenderId: '861577509887',
    projectId: 'ecommercesapp-14311',
    authDomain: 'ecommercesapp-14311.firebaseapp.com',
    storageBucket: 'ecommercesapp-14311.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA66wPHhuMS0uHRZxCKyee3H8ewAh_8Dw',
    appId: '1:861577509887:android:9f49e66e8cac91e1bec5ca',
    messagingSenderId: '861577509887',
    projectId: 'ecommercesapp-14311',
    storageBucket: 'ecommercesapp-14311.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0Rler4LY26j5O3WXRjGcdACCA3AfOTCA',
    appId: '1:861577509887:ios:6e518272327fbf3bbec5ca',
    messagingSenderId: '861577509887',
    projectId: 'ecommercesapp-14311',
    storageBucket: 'ecommercesapp-14311.appspot.com',
    iosBundleId: 'ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0Rler4LY26j5O3WXRjGcdACCA3AfOTCA',
    appId: '1:861577509887:ios:ad30546522683398bec5ca',
    messagingSenderId: '861577509887',
    projectId: 'ecommercesapp-14311',
    storageBucket: 'ecommercesapp-14311.appspot.com',
    iosBundleId: 'com.example.ecommercesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPdA-KTnqbFqWzy6xsbJ9mSPDc2Z_lMo8',
    appId: '1:861577509887:web:f34a051cb2f29aa2bec5ca',
    messagingSenderId: '861577509887',
    projectId: 'ecommercesapp-14311',
    authDomain: 'ecommercesapp-14311.firebaseapp.com',
    storageBucket: 'ecommercesapp-14311.appspot.com',
  );
}
